version: '3.9'

services:
  # Mongodb service
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - "4000:3000"
    environment:
      - PORT=3000
      - DB_CONNECTION_URL=mongodb://mongo_db:27017
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - mongo_db
